<?php
// the table of tasks are compose of following columns: id, title, description, status, priority, project_id, assigned_to, created_by, due_date
return [
    ['title' => 'Design User Interface', 'description' => 'Create wireframes and mockups for the main dashboard', 'status' => 'in_progress', 'priority' => 'high', 'project_name' => 'E-Commerce Platform', 'assigned_to_username' => 'john.smith', 'created_by_username' => 'jane.doe', 'due_date' => '2025-02-15'],
    ['title' => 'Database Schema Design', 'description' => 'Design and implement the database structure', 'status' => 'completed', 'priority' => 'high', 'project_name' => 'E-Commerce Platform', 'assigned_to_username' => 'alice.johnson', 'created_by_username' => 'jane.doe', 'due_date' => '2025-01-30'],
    ['title' => 'API Development', 'description' => 'Develop RESTful APIs for mobile integration', 'status' => 'pending', 'priority' => 'medium', 'project_name' => 'Mobile App Development', 'assigned_to_username' => 'george.lucas', 'created_by_username' => 'bob.wilson', 'due_date' => '2025-03-15'],
    ['title' => 'User Authentication', 'description' => 'Implement secure user authentication system', 'status' => 'in_progress', 'priority' => 'high', 'project_name' => 'Mobile App Development', 'assigned_to_username' => 'alice.johnson', 'created_by_username' => 'bob.wilson', 'due_date' => '2025-02-28'],
    ['title' => 'Data Visualization', 'description' => 'Create interactive charts and graphs for analytics', 'status' => 'pending', 'priority' => 'medium', 'project_name' => 'Data Analytics Dashboard', 'assigned_to_username' => 'diana.prince', 'created_by_username' => 'edward.stark', 'due_date' => '2025-04-15'],
    ['title' => 'Natural Language Processing', 'description' => 'Implement NLP algorithms for chatbot understanding', 'status' => 'in_progress', 'priority' => 'high', 'project_name' => 'AI Chatbot Integration', 'assigned_to_username' => 'george.lucas', 'created_by_username' => 'helen.troy', 'due_date' => '2025-03-01'],
    ['title' => 'Testing and Quality Assurance', 'description' => 'Comprehensive testing of all system components', 'status' => 'pending', 'priority' => 'medium', 'project_name' => 'E-Commerce Platform', 'assigned_to_username' => 'fiona.green', 'created_by_username' => 'jane.doe', 'due_date' => '2025-06-15'],
    ['title' => 'Documentation Writing', 'description' => 'Create user manuals and technical documentation', 'status' => 'pending', 'priority' => 'low', 'project_name' => 'Mobile App Development', 'assigned_to_username' => 'charlie.brown', 'created_by_username' => 'bob.wilson', 'due_date' => '2025-08-01']
];
